### ISSUE TITLE
Latest release crashes when trying to edit contact

### ISSUE THREAD

**Issue by HelmetOwl** [SimpleMobileTools/Simple-Contacts#1023]
The latest release crashes when trying to edit a contact. I downgraded to the previous release to verify it was the latest release.

Google Pixel 6A with GrapheneOS; APK from Github releases.

**Comment by tibbi** [comment]
when exactly does it crash? What OS version are you using?

**Comment by tibbi** [comment]
you mean that it crashes if you click on the photo placeholder, then click Choose photo and get back to the app after selecting the photo?

**Comment by tibbi** [comment]
I can reproduce the crash by trying to edit any existing contact now

**Comment by GerhardEric** [comment]
For incident of adding foto cause Contacts app to crash and not restart - I believe the foto size may be root cause.
Moment ago I edit Github profile by add foto. Foto I chose is large than 1 MB size. Github flash warning foto must be small than 1 MB for upload/update to succeed. Foto not upload. I resize foto to few 100 kb and upload succeed.

Might Simple Contacts (Tools) not test Contacts foto size limit and/or not create buffer to  warn to user or automatic resize/reducing foto to comply with Simple Contacts foto/data limits?

{I just try to help. Before I quit day job to be photographer I work in major telecom IT department for 15 yaers.}

**Comment by HelmetOwl** [comment]
> when exactly does it crash?

When I click the edit button, it sends me back to the contacts list. When I go back in and click it a second time, it crashes.

> What OS version are you using?

![version](https://github.com/SimpleMobileTools/Simple-Contacts/assets/86771201/aec41af5-f672-4e87-b779-f8ded535477d)

> I can reproduce the crash by trying to edit any existing contact now

My crashes had nothing to do with photographs.

**Comment by GerhardEric** [comment]
HelmetOwl & Tibbi 
sorry I email Simple Tools and they reply with this link to add my issue here.
