### ISSUE TITLE
Simple contacts pro crashes on startup after update (v6.22.6)(Playstore) 

### ISSUE THREAD

**Issue by robovoice1** [SimpleMobileTools/Simple-Contacts#1026]
type: crash
osVersion: google/raven/raven:13/TQ3A.230805.001/2023080800:user/release-keys
package: com.simplemobiletools.contacts.pro:106
process: com.simplemobiletools.contacts.pro
processUptime: 266 + 174 ms
installer: com.android.vending

java.lang.ClassCastException
	at a.b.A(SourceFile:1)
	at w7.t.f(SourceFile:89)
	at w7.v.c(SourceFile:727)
	at w7.h.f(SourceFile:660)
	at o1.w.run(SourceFile:37)
	at java.lang.Thread.run(Thread.java:1012)

Google Pixel 6 pro
Android 13 GrapheneOs latest stable release

**Comment by tibbi** [comment]
have you imported your contacts from some file?

**Comment by robovoice1** [comment]
Half a year ago i imported my contacts (vcf file) from my old phone (also simple contacts). 
Worked before, but now after the update from G.Play Store 
tge app crashes immediately.

**Comment by tibbi** [comment]
What contact source are you saving the contact to? I mean the last field at the contact details screen. Does it say your email, Phone, SIM or you had them at something like "Phone storage (not visible by other apps)"?

**Comment by robovoice1** [comment]
Phone storage (not visible to others) if i remember correct.

**Comment by tibbi** [comment]
hm ok, weird... You cannot uninstall the app then, else they will e deleted.

**Comment by ContactsUser** [comment]
Same happened to me: "Simple Contacts Pro", installed more than a year ago on a OnePlus Nord 2, now with Android [OxygenOS] 13.
After an app update of "Simple Contacts Pro" to v.6.22.6 this morning (2023-09-04), the app doesn't start (i.e., stops/crashes at start).
All my contacts were created manually within "Simple Contacts Pro" (i.e., not read from any file), and are stored in "Phone storage (not visible by other apps)".
The crash happened for the first time after the app update (no new contacts have been created since the update).

**Comment by robovoice1** [comment]
After 6.22.7 update i have access to my contacts 👍😎
Thanks for the fast update!
