### ISSUE TITLE
[Bug] Different export formats

### ISSUE THREAD

**Issue by HarriBuh** [SimpleMobileTools/Simple-Contacts#1043]
..between auto backup and manual backups.
This became obvious to me when I tried to manually import an (auto-)backup after resetting my phone and it **failed**.

The two vcf-files will look like this:
![Screenshot_20231009-155141](https://github.com/SimpleMobileTools/Simple-Contacts/assets/123186113/8eb528e7-eea9-4ae6-9748-67a66251af97)

As one can clearly recognise, there is a difference both in language and size.

When opening these two files, the formatting is completely different,too:

![markup_1000000853](https://github.com/SimpleMobileTools/Simple-Contacts/assets/123186113/5fd38166-7677-4e20-bbf4-7c94eab4840a)
![markup_1000000854](https://github.com/SimpleMobileTools/Simple-Contacts/assets/123186113/87389f40-2cd2-438b-8af8-506fe9baa0c7)

The real issue here is that importing an auto-backup won't work (some error message saying "wrong formatting" or else).

Google Pixel 7
Android 14
App version: 6.22.7

**Comment by mooreye** [comment]
I just came here to report this, as import of automatic backups fails, while manual backup restores just fine.

This seems like a major issue.

**Comment by sfSfabiano** [comment]
Olá
Comigo também e agrava que nao consigo capturar o codigo de erro. Illegal java...
Nao importa o backup vcf
Pixel 6a
Android 14

Hello With me too and aggravates that I can't capture the error code. Illegal java... No matter vcf backup Pixel 6a Android 14

Uploading 1_5001745383357940891.mp4…

**Comment by otizonaizit** [comment]
Hi! First, thank you for this great app! I am affected by the very same bug, so I was wondering why this issue has been closed?
The reproducer is pretty simple:

- enable automatic backup in the app
- wait one day so that an automatic backup is created
- delete all your contacts from the app
- import the automatically created backup file
- the import fails with an error

as others have noted already, if you manually export the contacts, a VCF file is created. This file can be re-imported in the app, so this is an effective backup. The automatically created backup is actually not a VCF file but a JSON file, and while all the data is still in there, the app fails to import this format.

I I am using the app version 6.22.7 Pro from F-Droid.

**Comment by inson1** [comment]
@otizonaizit SMT apps were sold to ad company. Fork is here https://github.com/FossifyOrg. Release will be in about 1 week.

**Comment by Sfcyber** [comment]
Ok lido.
