### ISSUE TITLE
Support nicknames

### ISSUE THREAD

**Issue by Atalanttore** [SimpleMobileTools/Simple-Contacts#248]
Simple-Contacts doesn't seem to support nicknames in the address book.

Regards,
Atalanttore

**Comment by michaelof** [comment]
@Atalanttore

"Search" before "Open" might be a good idea ;) 

Nickname exists already, but as not everyone needs it, it must be enabled in settings/visible contact fields.

**Comment by tibbi** [comment]
Can you try exporting a contact with nickname in a .vcf file and pasting here lines starting with "N:" or "FN"? Censor out the fields if you want.
If you add a nickname in Simple Contacts, does it show up at other apps?

**Comment by michaelof** [comment]
SimpleContacts: 4.4.0 
Nextcloud: 14.0.0
DAVdroid: 2.0.3-ose
Android 6.0

*** No issue here ***

Steps performed:
1. Enabled Nickname in SimpleContacts
2. Added new contact with nickname set
3. Synched to Nextcloud via DAVdroid
4. Fine in Nextcloud, made some changes, also to nickname
5. Synched back to SimpleContacts via DAVdroid

Result: Fine in SimpleContacts, all changes synched in both directions

Tried additionaly to start test by creating a contact in Nextcloud, instead of SimpleContacts, same positive result.

Remark: Tested a little also with stock contacts app. Nickname is a visible column when a value was set before in either SimpleContacts or Nextcloud. But it seems that my stock contacts app does offer nickname field when creating a new contact or change a contact with empty nickname. Stopped testing at that point

**Comment by michaelof** [comment]
![screenshot_20180910-221406](https://user-images.githubusercontent.com/15951622/45323691-3d933680-b54c-11e8-9b51-d51855dbdbda.png)
![screenshot_20180910-221607](https://user-images.githubusercontent.com/15951622/45323713-4c79e900-b54c-11e8-974c-94cf863f929c.png)
![screenshot_20180910-221659](https://user-images.githubusercontent.com/15951622/45323724-569be780-b54c-11e8-8c73-cca893ced597.png)
![screenshot_20180910-221735](https://user-images.githubusercontent.com/15951622/45323733-5f8cb900-b54c-11e8-9a67-fb39bc88ec6b.png)

**Comment by Atalanttore** [comment]
I think I've found the problem. It seems to be a misleading GUI in another application where the fields _displayname_ and _nickname_ are mixed up.

**Comment by tibbi** [comment]
ye nicknames are already supported, what is missing are Phonetic names.

**Comment by Atalanttore** [comment]
Is there a chance to get phonetic names in Simple-Contacts?

**Comment by tibbi** [comment]
ye, ill take a look at it someday

**Comment by contrapunctus-1** [comment]
To prevent situations like this and to improve discoverability, why not add a plus button below the first and last name, which adds these fields?

This is also how the Google Contacts app does it. 🙂
