### ISSUE TITLE
Feature Request: Contact Sources

### ISSUE THREAD

**Issue by Phoenix1747** [SimpleMobileTools/Simple-Contacts#25]
Like I said before in #24, I don't know what you planned but here's my other suggestion!

It would be neat if one could choose all the sources that the contacts would be indexed from like SIM only, or device and SIM, etc.

**Comment by Natrinicle** [comment]
I'd like to second this feature request. Signal shows up as duplicate contacts in this app because it uses the main contact book to look up other Signal users. I'm also in the middle of switching from Google Contacts to Nextcloud and get 2-3 duplicate contacts from various sources on most of my contacts. It would be nice to have something like in the calendar app that allows you to turn on and off sources to sync with.

**Comment by tibbi** [comment]
you can already filter out contacts by source. Just go to the first or second tab and select Filter.

**Comment by Natrinicle** [comment]
Ah! After tapping around I finally found it! Thanks for the hint, the icon looked like another sort icon so I hadn't tried it.

**Comment by tibbi** [comment]
ye sorting and filtering icons are similar, but they are the standard icons used by most good apps so they should be intuitive.
