### ISSUE TITLE
Dialer is without any effect

### ISSUE THREAD

**Issue by Coronarius** [SimpleMobileTools/Simple-Contacts#386]
On my Xiaomi smartphone contacts are OK. But dialing is without any effect. Even displaying IMEI with  * # 0 6 #  fails. Dialing numbers seems to work (phone icon is "pulsing"), but waiting some minutes does't help. There are neither error messages in application nor in logcat. Dialer pad touch tone is also missing. Looks like dialer is a fake app (I know it's not). Realy strange.

Built-in MIUI contacts+dialer app has no problems. 

Phone model: Xiaomi REDMI 5 plus with Oreo 8.1.

**Comment by tibbi** [comment]
Have you set the app as the default app for handling calls?

**Comment by aGrimRepoMan** [comment]
Some data points from a Xiaomi Redmi Note 5 (global version) running 8.1.0 (MIUI 10.2.2.0)
1. "Contacts" dialler is working (calls complete okay) for normal numbers.  
2. There are no tones produced by the dialler.
3. IMEI display via *#06# doesn't work.  I see the following 2 messages in sequence:
   a) "USSD Code Running"
   b) "Connection problem or invalid MMI code

["Contacts" app is not the default dialer, i.e., I choose to use it each time instead of the native dialler.]
(IMEI display via *#06# works fine on the native dialer).

**Comment by tibbi** [comment]
well, Im not sure why dont IMEI codes work, it could be some device specific issue :/

**Comment by philippHRO** [comment]
I have the same problem. When I try to dial from Simple Contacts Pro (F-Droid) it shows the "complete action using" dialogue. This allows to choose "dialer" (from simple contacts) and the built-in dialer.

Choosing dialer results in an error message being displayed on the screen (it's in german for me; it's translated "No matching app found").

I have a Samsung S4.

**Comment by tibbi** [comment]
should be fixed in 6.10.0 released soon
