### ISSUE TITLE
No call screen shown while placing calls

### ISSUE THREAD

**Issue by jotbeh** [SimpleMobileTools/Simple-Contacts#490]
Hello Tibor, 

I tried replacing Google's _Phone_ and _Contacts_ app with _Simple Contacts_ on my Moto G7 power (XT1955-4, Android 9). However, when I place a call, even though the call connects and I can see/hear it on the called device, there is no call screen or dialog on my phone that would allow me to hang up, mute, etc. .
I disabled Google Play Services on my phone, if that is relevant. Does _Simple Contacts_ simply not have a call screen yet or is there anything I can do?

Thank you for your support and all you do!
J.B.

**Comment by tibbi** [comment]
there is no call screen as it would require a lot more work related to the call functionality too, not just some UI. It tries using some predefined call screen, that might be missing in your case. If you enable Google Play Services, does it work?

**Comment by jotbeh** [comment]
Thank you for your reply. The calling screen seems to be provided by the Google Phone app. Maybe at some point you can think about writing a _Simple Dialer_ app, as I haven't found an open source replacement for the Google Phone app yet. I know this is not the right place, but if you know of any, I would appreciate you letting me know.
Have a nice day.

**Comment by tibbi** [comment]
well ye, it is on the roadmap. I wanted to implement a dialer already in Simple Contacts, but it had many device specific issues as manufacturers like doing things differently. Having an unreliable dialer would be a pretty bad thing so I just postponed the whole dialer for now. The app also has no access to call logs due to Googles latest permissions policy. I requested it already multiple times but it was always rejected.

**Comment by ltGuillaume** [comment]
Have you seen this by any chance? https://github.com/arekolek/simple-phone

**Comment by tibbi** [comment]
Not really, does it work? Looks quite abandoned and unpopular.

**Comment by ltGuillaume** [comment]
It's a proof-of-concept, really, so I don't think it would be a problem that the latest commit is from a year ago, especially since it's been updated for Android 10.

It may not be useful to implement directly as a good-to-go solution, but it could act well as a framework of sorts to get you going. It's only a few lines of code, really, and the documentation seems quite ok.

**Comment by tibbi** [comment]
I already had a basic implementation of the dialer, but it had many device specific issues. This might be a proof of concept working on the developers devices, but I dont think it has ever been used by real users. There are just many things handled differently per manufacturer, which is a lot harder to solve than with a few lines. Already storing contacts has many different ways. Will take a look at it someday though.

**Comment by ltGuillaume** [comment]
Yeah that's undoubtedly the case. Might give some new insights though, who knows? 😃

**Comment by tibbi** [comment]
should be fixed in 6.10.0 released soon
