### ISSUE TITLE
Wrong letter is displayed when tapping on the letter in the right column

### ISSUE THREAD

**Issue by OpenWarp** [SimpleMobileTools/Simple-Contacts#564]
I case of a phone book containing a mix of Latin and non-Latin character set contacts, touching the corresponding letter in the right column results in wrong letter popping up and accessing the wrong page of a phone book. To reproduce, 
1. Import both Latin and non-Latin contact names into the app.
2. Observe the letters in the right column. There is not enough space for all letters from two alphabets to be displayed and no way to scroll the column up and down
3. Press on the desired letter in the right side alphabet column
4. Observe the wrong letter pop up in the colour circle, usually way down the list

**Comment by tibbi** [comment]
Give some example names for reproducing please

**Comment by OpenWarp** [comment]
I had generated a test file which goes to "Z" page when pressing "K" on the right. The test file has 30 entries for each letter. Feel free to experiment with varying number of contacts as well as having no contacts for some letters.
[test.vcf.gz](https://github.com/SimpleMobileTools/Simple-Contacts/files/4640469/test.vcf.gz)

**Comment by tibbi** [comment]
right, it is caused by not enough space indeed. Not sure what could be done about it though, I like the current way. It is still easier to scroll down than making the letters too tiny.

**Comment by tusch001** [comment]
This is also happening when there are only latin letters in the names (tapping on T results in W). On my display the letter W is the last one visible although not accessible because it is overlaid with the + button. The behaviour is worse when the keyboard is open (searching for a name), then the last accessible (i.e. tappable) is the letter D which results in an R.
> It is still easier to scroll down than making the letters too tiny.

Is it an option to make the letters scrollable? I have > 500 entries in my phone book and scrolling to reach the end is a bit annoying.

**Comment by tibbi** [comment]
proper contact should be shown at using scrollbar already, clipping it at too many entries is a different issue
