### ISSUE TITLE
Add option for disabling merging

### ISSUE THREAD

**Issue by rEnr3n** [SimpleMobileTools/Simple-Contacts#582]
Just putting this here on its own thread. Taking from the comments at #446

> For me the duplicate merging is now too aggressive. I have two contacts with same name First name and same Surname and those are now merged. This should not happen - these two contacts have different display name, organizations, phone numbers, emails, 

> I also want to confirm that the current merge method is too aggressive. I have checked my contacts and I have 170 "duplicates" according the new merging method. For example, I use names like "IT-Support", "Headquarter", "Sales" as same last name but for different companies which I have contacts. They all get merged together, although they clearly do not belong together. Also, there are some persons who really have same names but are totally different individuals.

**Comment by michaelof** [comment]
IMHO +1 for this feature request, as e.g. I've just recognized that information is lost: 

- Have two independent contacts which have been auto-merged.  
- Merge combines email adresses. phone# etc. of both source contacts: would be fine if merge was wanted
- Merge drops "NOTE" vcard node from 2nd (new) contact, keeps note of existing before contact only.

**Comment by tgiddings** [comment]
I just bought the app in part because of the merge feature, and came here looking to figure out how to use the merge feature.

Learning that it is automatic and forced is... frightening. Merging is destructive editing. Destructive editing needs consent.

It's also inflexible -- I'm not going to futz with the names of contacts until the app figures out that I want them merged.

This is looking like a very early deal-breaker for me.

**Comment by Leynch** [comment]
+1 for this feature.
Its not only that contacts get merged which shouldn't but also when the merged ones get synced it's messing up my categories and other fields ... 
Please make an off-switch available!
