### ISSUE TITLE
Null Pointer exception for vcard import

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Contacts#622]
Extending #621 

v6.13.0 F-Droid
Android 10, Nokia 7.2

Trying to import a bare minimum but compliant to RFC 6350 V4.0 vcard:
```
BEGIN:VCARD
VERSION:4.0
FN:Först Last
TEL;VALUE=uri;TYPE="CELL":tel:+491234567890
TEL;VALUE=uri;TYPE="VOICE,HOME":tel:+499876543210
END:VCARD
```

leads to a
```
java.lang.NullPointerException: number must not be null
```

Same vcard imports fine to my Nextcloud (20.0.1 on OpenSuse Leap 15.2).
Nextcloud exports as V3.0:

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.3.0//EN
FN:Först Last
TEL;TYPE=CELL:tel:+491234567890
TEL;TYPE="VOICE,HOME":tel:+499876543210
UID:444b38a4-3bda-4a53-a9e7-c40d357f69b5
REV;VALUE=DATE-TIME:20201028T122702Z
END:VCARD
```
which leads to the same Simple-Contacts NullPointerException when trying to import.

**Comment by forensicolten** [comment]
Having the same (or similar?) problem.

Importing a v4.0 vCard results in the following:
`Importing...`
`An error occurred:
java.lang.NullPointerException: it.date.must not be null`
`Importing some entries failed`

This should be up to standards, it's a vCard exported from Thunderbird.


Interestingly, when I manually change all the version entries in the vCard from 4.0 to 2.1, it does import the file.

**Comment by tibbi** [comment]
please send a sample at every error, else I cannot reproduce it. Just open the text file with any text editor and try figuring out at which contact does it happen

**Comment by tibbi** [comment]
many importing things have been solved already since then, reopen if it is still broken

**Comment by GaneshkumarOPTISOL** [comment]
Hai @tibbi I have faced the issue here, Kindly look into this and also I have attached my screenshot for reference

![2022_02_24_11_55_26](https://user-images.githubusercontent.com/77052611/155479791-f4baa44b-42af-4b76-bc66-7ef0746706f4.jpg)

This is the response I got while scanning my files, when I need to fetch it from the vcard it shows a nullpointer exception, 

![Screenshot (190)](https://user-images.githubusercontent.com/77052611/155480108-38f38bb1-e615-4773-bfb9-220f452dfd0e.png)
