### ISSUE TITLE
Unable to access native phone contacts

### ISSUE THREAD

**Issue by yannicka** [SimpleMobileTools/Simple-Contacts#623]
The application does not have access to the phone's contacts, only to the application's contacts.

This is the filter that displays only this:
![Screenshot_20201031-155507-2](https://user-images.githubusercontent.com/22885898/97783060-8297de00-1b95-11eb-9492-05c70073c3fe.png)

- Version: 6.13.1 Pro
- Android 10
- Informations: my phone is not signed in to a Google Account

**Comment by tibbi** [comment]
and have you granted the Contacts permission at launching? Do other downloaded apps show the other contacts too?

**Comment by yannicka** [comment]
Yes, the Contacts permission is allowed.
The native applications Contacts and Simple Dialer can access to natives contacts.

**Comment by Nils6852** [comment]
Same issue here:
Nokia 7.2, Android 10, App version F-Droid: 6.15.0 Pro, no login to Google Account
I only can create invisible a contacts. The App has the right permissions.
![grafik](https://user-images.githubusercontent.com/72854099/121392470-b8811a00-c94f-11eb-81c4-4dab47469d1c.png)
I import some contacts with "DW Contacts" and these are not shown in Simple Contacts.
I can create contacts with the non Pro app. But it don't shows the entry too.

On my old android 8 device all works perfect. I think the problem is on Android 10 or missing Google login.
I hope you can fix the bug.

**Comment by yannicka** [comment]
I still have the problem. It's even stranger because the Simple-SMS-Messenger and Simple-Dialer applications have access to native contacts.
