### ISSUE TITLE
Allow sorting by date created or last modified

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Contacts#71]

**Comment by tibbi** [comment]
the only related field at contacts is LAST_TIME_USED

**Comment by qwertyfinger** [comment]
@tibbi `LAST_TIME_USED` is deprecated from API 29 and not available in published apps on any API level.
https://developer.android.com/reference/android/provider/ContactsContract.ContactOptionsColumns#LAST_TIME_CONTACTED

There is a `CONTACT_LAST_UPDATED_TIMESTAMP`: https://developer.android.com/reference/android/provider/ContactsContract.ContactsColumns#CONTACT_LAST_UPDATED_TIMESTAMP.

But judging from this StackOverflow answer, it's pretty useless since it gets updated all the time when some background sync happens without the user actually changing anything: https://stackoverflow.com/a/57489435

The only somewhat viable option seems to be keeping our own cache of hashcodes for contacts, periodically check if they have changed, and record the timestamp of when that happened. But it seems too complicated and error-prone for such a small feature.

**Comment by qwertyfinger** [comment]
On the other hand – installed this app and it seems to sort by created date, and even shows some contact entry number: https://play.google.com/store/apps/details?id=ibtidah.tav.reco.
Will investigate further.
![image](https://user-images.githubusercontent.com/7561414/129554785-5cc523de-1b4b-4886-8d5f-f58de956346c.png)

**Comment by tibbi** [comment]
well it has been updated in 2019 the last time, guess that field was still available. And as they arent updating targetSDK anymore, it still works. We have some locally stored contacts too that are fully under our control, but it isnt worth adding for them only. You can try fetching all fields with "*" and parsing through the whole cursor to see if there is nothing useful. We could rely on the "ID" itself too as we dont really need the date and time, just their order.

**Comment by qwertyfinger** [comment]
Yep, I just confirmed that this is how this apps works – it just sorts by contact's ID.

**Comment by tibbi** [comment]
we can rely on that too. We won't be able to mix the public contacts and ones stored in "Phone storage (not visible by other apps)", but I dont think it matters. People usually dont mix those either, just use one or another.

**Comment by tibbi** [comment]
duplicate contact merging under the hood is a really messy thing, a contact could be merged from contacts with IDs like 3, 16 and 56. Do not change the way it is done now though, let's just use the ID that is used at showing the given contact on the main screen now.

**Comment by qwertyfinger** [comment]
There are 2 different contact ID fields:
1. `RAW_CONTACT_ID` - https://developer.android.com/reference/android/provider/ContactsContract.DataColumns#RAW_CONTACT_ID
2. `CONTACT_ID` - https://developer.android.com/reference/android/provider/ContactsContract.RawContactsColumns#CONTACT_ID

Sometimes they contain different values, sometimes the same ones.
I tried sorting by both of them and `RAW_CONTACT_ID` seems to give correct results for much more contacts, although for some contacts comparison by `CONTACT_ID` is correct instead.
So I propose to use `RAW_CONTACT_ID`, although it's still not a perfect solution.

**Comment by qwertyfinger** [comment]
@tibbi What's the purpose of this SQL sort function? To get at least partially sorted list of contacts and then sort them again using `compareTo()`? For example, if I change it to always return `Phone.NUMBER`, sorting still works the same as before.
https://github.com/SimpleMobileTools/Simple-Contacts/blob/90903744da7f955f970b6116fd24f1dc115b79aa/app/src/main/kotlin/com/simplemobiletools/contacts/pro/helpers/ContactsHelper.kt#L841

**Comment by qwertyfinger** [comment]
When syncing between devices, IDs seem to get changed too. So if you're moving to a new phone, your contact IDs will be recreated.

**Comment by tibbi** [comment]
not sure, I guess I used 2 ways just as an extra check. Well, sorting by ID can have some glitches, but it is the best we can do so whatever :) Will be fixed in 6.15.1
