### ISSUE TITLE
Serious bug = Data loss: deleting contact actually removes all entries withe the same name

### ISSUE THREAD

**Issue by lfom** [SimpleMobileTools/Simple-Contacts#872]
Hello!

Once again, thank you for providing the apps for free, the private contacts lists is a great idea. I wanna report a serious bug regarding contact management in Contacts 6.21.0 Pro. How to reproduce the problem:

1. Create two contacts with the same name, for instance first name = A, last name = X (so it appears in the top of the list), one with only the phone number and the other with just an email
2. Edit the second contact and add a phone number
3. Delete the first one with only the phone number
4. Result: both contacts are gone

This is a serious problem, I hope this can be fixed soon.

Regards

**Comment by tibbi** [comment]
3. are you deleting from the edit or view screen?

**Comment by lfom** [comment]
@tibbi I have just tested it here: the problem happens either if I delete the contact while it is selected in the list or viewing the contact details, but _not_ when editing the contact that will be deleted (edit first, then delete).

By the way, there is also a bug that once the keyboard shown while editing an item, the top bar with the icons is moved upwards and gets somewhat hidden, it's required to hide the keyboard (or "go back" ) first in order to be able to save.

**Comment by tibbi** [comment]
right, so that isnt a bug. Edit screen deletes just the specific contact instance, but View screen or the list view deletes them all

**Comment by lfom** [comment]
@tibbi I am sorry, but this is not the expected behavior nor what the vast majority of other similar apps do: if a contact is selected (or active in the details view) and delete is used then only the selected (or active) item us supposed to be removed. There is no info anywhere that all items with the same name will be removed. Just to be clear, not even the option to merge contacts was enabled, so deleting all items with the same name is not the expected behavior at all.

**Comment by vepain** [comment]
Hello!

I think this issue should be re-open.

> I am sorry, but this is not the expected behavior
I agree with @lfom
At least, a warning message is necessary, but I think this issue should not be asked.

In fact, if you want to move a large amount of contact from `A` to `B`, you have to export `A` first then import to `B`.
And then, the idea is to remove the duplicated contact in `A`.

1. you can't remove from the view with selecting from a filter just `A`, because of this behaviour 
2. if you want to remove one by one in `A`, even if you edit first, removing contact `A` remove the duplicated contact in `B`, while the merge option is not selected (perhaps because of contact uid?)

One solution can be:
- if you select the merge option, then removing a contact (even in a filter view) can remove its clone in all the other places
- if the merge option is false, then removing a contact from a filter view **must not** remove its clone in the other places.

Thank you for this app, I think this can be a great upgrade :)

**Comment by lfom** [comment]
Yes, this causes data loss and should be changed. There's no info anywhere that deleting the contact being visualized/edited will also delete every other contact with the same name.

**Comment by tibbi** [comment]
the fact that the contact will be deleted from all contact sources is written directly at the confirmation dialog.

**Comment by lfom** [comment]
@tibbi Deleting the current contact from all sources is not the problem. The problem is that all other contacts with the same name will also be removed from all sources, causing data loss. This can be reproduced using the steps in my previous post or the ones in @vepain post as well.

**Comment by vepain** [comment]
> the fact that the contact will be deleted from all contact sources is written directly at the confirmation dialog.

In french it is only written "Are you sure to delete the contact?"
Perhaps in english it is clearer.

**Comment by tibbi** [comment]
> > the fact that the contact will be deleted from all contact sources is written directly at the confirmation dialog.
> 
> In french it is only written "Are you sure to delete the contact?" Perhaps in english it is clearer.

thats when you delete from the Edit screen, only 1 single contact is deleted. Multiple ones are deleted only at the View Details screen

**Comment by lfom** [comment]
@tibbi Sorry, but you still didn't get it... You do not have many contacts with the same first name, people you do not ask the last name, etc? For instance, I have three contacts named Tibor, with different phone numbers and address, they have the same name but they are different contacts. If I remove one of them from the contacts list, **all of them are deleted, causing data loss**. _There is no info anywhere warning that this will happen!_ Of course, there is a warning that deleting a contact will remove it from the list, **but there no info anywhere that all three conatcts named Tibor will be deleted from the app!**

**Comment by vepain** [comment]
> thats when you delete from the Edit screen, only 1 single contact is deleted. Multiple ones are deleted only at the View Details screen

I tested all the delete cases, and I have the same result (duplicated contact from different account are all deleted) and the same french warning message

**Comment by lfom** [comment]
Also, every other Contacts app on Earth (as well as any other app with items on a list) only deletes the item that is being displayed. There is no reason at all to silently delete all items with the same same name. This is not expected at all.

**Comment by lel-amri** [comment]
I'm agree with the idea that deleting all contacts with a related name isn't what I expect a contacts app to do (any app actually). When I want to delete an entry, I want only this entry to be deleted, not other entries that the application think are related. Deleting "related" entries is kind of evil actually :/
I hopefully backup my data, otherwise I'd have just lost the 5 "Anne" I have in my contact book (that I can distinguish thanks to the notes).
