### ISSUE TITLE
feature request: generate display name from contact informations

### ISSUE THREAD

**Issue by volker-raschek** [SimpleMobileTools/Simple-Contacts#94]
Hey, 
I have a suggestion for improvement again. 

When I edit a contact, I see only the given name, secondary name and surname. But what is with the prefix name (for example a doctor title), the suffix name (for example aristocratic title) and the nickname of a contact. I missed this fields.

When I have a contact with all this name information's, it's would be great if I can select for every address book how the display name would be generated.

So I manage a address book of an university over CardDav for the employees and they want an other display name as my own contacts. 

For example:
university contacts begins with: prefix, given name, secondary name, surname, suffix name
my private contacts begins with: given name, secondary name, surname

**Comment by tengwar** [comment]
+1 for supporting prefixes, suffixes and all the other name-related stuff that Android's default Contacts app allows. Another common use case would be to display a pseudonym instead of a name (if available of course). This allows me to keep someone's full name for contact deduplication purposes but display them the way I use to call them.

**Comment by tibbi** [comment]
Prefixes and suffixes will be added in 3.5.0 released soon. You will have to enable it in Setting -> Manage shown contact fields, as it will be hidden by default.
